services:
  backend:
    build:
      context: ./backend
    container_name: harish-portfolio-api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: harish-portfolio-web
    depends_on:
      - backend
    ports:
      - "8080:80"
